# Generated by Django 2.2.4 on 2019-09-03 00:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantSoilMoistureMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('measurement', models.DecimalField(decimal_places=1, max_digits=4)),
                ('plant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soil_moisture_measurements', to='plants.Plant')),
            ],
        ),
    ]
