# Generated by Django 2.2.4 on 2019-09-15 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_auto_20190915_0235'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AirMeasurement',
        ),
    ]
